site_name: TARDIS Connector
site_description: TARDIS Connector 2025 Workshop
repo_url: https://github.com/tardis-sn/connector25
site_author: TARDIS Connector

theme: 
  name: material
  logo: assets/tardis-logo-2.svg
  favicon: assets/tardis-logo-2.svg

plugins:
  - mkdocstrings
  - mkdocs-jupyter
  - search

nav:
  - ğŸ  Home: index.md
  - ğŸ”§ Installation: installation.md
  - ğŸ–¥ï¸ Run the Connector on HPCC: running_on_hpcc.md
  - ğŸ—ï¸ The Connector Pipeline:
    - MESA â†’ STIR: mesa_to_stir.md
    - STIR â†’ STELLA: stir_to_stella.md
    - STELLA â†’ TARDIS: stella_to_tardis.md

copyright: Copyright &copy; 2025 TARDIS Connector